eskenas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
     url(r'^admin/', include(admin.site.urls)),

     url(r'^$', 'myprofile.views.index'),
     url(r'^home/$', 'myprofile.views.myLogin'),
     url(r'^home/register/$', 'myprofile.views.register'),
     
     url(r'^transaction/$', 'transaction.views.transaction'),
     url(r'^transaction/add/$', 'transaction.views.addTransaction'),
     url(r'^transaction/delete/$', 'transaction.views.deleteTransaction'),
     url(r'^transaction/edit/$', 'transaction.views.editTransaction'),
     url(r'^transaction/addBankAccount/$', 'transaction.views.bankAccountAdd'),
     url(r'^transaction/delBankAccount/$', 'transaction.views.bankAccountDel'),
     url(r'^transaction/editBankAccount/$', 'transaction.views.bankAccountEdit'),

     url(r'^auto_transaction/add/$', 'transaction.views.addAutoTransaction'),
     url(r'^auto_transaction/delete/$', 'transaction.views.deleteAutoTransaction'),
     url(r'^auto_transaction/edit/$', 'transaction.views.editAutoTransaction'),
     
     url(r'^logout/$', 'myprofile.views.logout_view'),
     url(r'^profile/edit/$', 'myprofile.views.edit'),
     url(r'^profile/ertegha/$', 'myprofile.views.ertegha'),
     url(r'^profile/tamdid/$', 'myprofile.views.tamdid'),
     url(r'^profile/changepass/$', 'myprofile.views.changePass'),
     url(r'^profile/$', 'myprofile.views.profile'),
     
     url(r'^report/$', 'report.views.general'),
     url(r'^ajax/monthly_report/$', 'report.views.monthly'),
     url(r'^ajax/transaction_report/$', 'report.views.getTransaction'),
     
     url(r'^budget/$', 'budget.views.budgetForm'),
     url(r'^budget/add/$', 'budget.views.budgetAdd'),
     url(r'^budget/del/$', 'budget.views.budgetDel'),
     url(r'^budget/edit/$', 'budget.views.budgetEdit'),


     url(r'^auto_transaction/$', 'transaction.views.autoTransCheck'),
     
)

cat/models.py
from django.db import models
from django.contrib.auth.models import User


class Cat(models.Model):
    name = models.CharField(max_length=50)
    isSub = models.BooleanField(default = False)
    parentCat = models.ForeignKey('self', default = None, null=True, blank=True)
    user = models.ForeignKey(User)
    
    def __unicode__ (self):
        return self.name

class BankAccount(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name

cat/templates/catForm.html
<!doctype html>
<html>
<body>
	<form action='.' method="post">
		<input name= "formID" value="1" type="hidden">
		<input name="name" placeholder="نام دسته" type="text"><br>
		<input type="submit">
	</form>
	<ul>
		{% for c in cats %}
        	<li>
        		{{c.name}}
        		
        			<form action='.' method="post">
					<input name= "formID" value="4" type="hidden">
					<input name= "id" value="{{c.id}}" type="hidden">
					<input name= "new" type="text" placeholder="نام جدید">
					<input type= "submit" value="تغییر">
					</form>
					
        		<ul>
        			{% for b in c.cat_set.all %}
        			<li>
        			{{b.name}}
        			<form action='.' method="post">
				    	<input name= "formID" value="3" type="hidden">
						<input name= "id" value="{{b.id}}" type="hidden">
						<input type="submit" value="حذف">
					</form>
					
					<form action='.' method="post">
					<input name= "formID" value="4" type="hidden">
					<input name= "id" value="{{b.id}}" type="hidden">
					<input name= "new" type="text" placeholder="نام جدید">
					<input type= "submit" value="تغییر">
					</form>
					
        			</li>
        			{% endfor %}
				    <form action='.' method="post">
				    	<input name= "formID" value="2" type="hidden">
						<input name="name" placeholder="نام زیر دسته" type="text"><br>
						<input name= "parent" value="{{c.id}}" type="hidden">
						<input type="submit">
					</form>
        		</ul>
        	</li>
    	{% endfor %}
	</ul>
</body>
</html>